Post stuff
alexcogojocaru/social-network-app pull request #17
Opened 2021-04-28 17:39 UTC by BogdanCosminBarbu

2021-04-28 18:04 UTC, paraschevanegru approved these changes

2021-04-29 08:58 UTC, alexcogojocaru requested changes

2021-04-29 08:58 UTC, alexcogojocaru commented on Controllers/PostController.cs
> +        private static IComment _commentService = new CommentService();
pls remove unused services

2021-04-29 08:58 UTC, alexcogojocaru commented on Controllers/PostController.cs
> +            if ((post == null) || (_postService.GetPost(post.Id) == null))
here it should be only post == null

2021-04-29 08:59 UTC, alexcogojocaru commented
also check why the get request doesn't work

2021-04-29 11:44 UTC, alexcogojocaru requested changes

2021-04-29 11:44 UTC, alexcogojocaru commented on Models/PostEntity.cs
> +        [JsonProperty("content")]
why content?

2021-04-29 11:48 UTC, alexcogojocaru requested changes

2021-04-29 11:48 UTC, alexcogojocaru commented on Controllers/PostController.cs
> +using Microsoft.AspNetCore.Mvc;
add a header

2021-04-29 11:48 UTC, alexcogojocaru commented on Interfaces/IPost.cs
> + *  Copyright:   (c) 2021, Cojocaru Daniel-Alexandru                      *
i didn't write this

2021-04-29 11:48 UTC, alexcogojocaru commented on Models/PostEntity.cs
> + *  Copyright:   (c) 2021, Cojocaru Daniel-Alexandru                      *
or this

2021-04-29 11:48 UTC, alexcogojocaru commented on Services/PostService.cs
> + *  Copyright:   (c) 2021, Cojocaru Daniel-Alexandru                      *
pls add your name :(

2021-04-29 11:48 UTC, alexcogojocaru commented on UnitTests/PostServiceUnitTest.cs
> + *  Copyright:   (c) 2021, Cojocaru Daniel-Alexandru                      *
and here 🥇

2021-05-05 11:06 UTC, alexcogojocaru approved these changes

2021-05-05 11:22 UTC, merged